
// This file is automatically generated

export const METADATA = {
  "name": "react-native-agent",
  "version": "0.0.1",
  "versions": {
    "react-native-agent": "0.0.1",
    "openai": "^6.26.0"
  }
};

export default METADATA;
